#!/usr/bin/env python3
"""Generate the Geneva summit hall for the playable UI (owner pick 2026-09-26: style 3, over your shoulder).

Writes ui/assets/summitArt.js: the hall pieces as strings, with three faces and three placards per delegate
(sign, unsure, no) so the summit screen can show each delegate's lean. Colours are token mixes only.
"""
import json
import os

import gen_office as G
import gen_president as GP
import gen_summit_styles as S

SCALE = 2.5
LEANS = ("yes", "maybe", "no")


def hall_back():
    back = S.hall_back("sh")
    # The summit screen draws its own text over the frame.
    start = back.index('<text x="720" y="142"')
    end = back.index('</text>', back.index('Motion 1 ·')) + len('</text>')
    return back[:start] + back[end:] + S.flags()


def seats():
    out = []
    for pid, x in zip(S.ORDER, S.XS):
        c = S.CAST[pid]
        oy = S.desk_top_y(x) + 30 * SCALE
        suit = G.M(S.PARTY[pid][2], 38, "ink")
        p = dict(skin=c["skin"], hair=c["hair"], style=c["style"], shirt=suit, mood="calm", suit=True, glasses=c["glasses"])
        body, hands, (hx, hy) = G.front_person(p)
        wrap = lambda inner: f'<g transform="translate({x},{oy:.1f}) scale({SCALE})">{inner}</g>'
        head = [round(x + hx * SCALE, 1), round(oy + hy * SCALE, 1)]
        out.append({
            "id": pid,
            "head": head,
            "body": S.chair_back(x, oy, SCALE, pid) + wrap(body),
            "faces": {lean: wrap(S.cari_head(hx, hy, c, lean)) for lean in LEANS},
            "hands": wrap(hands),
            "placards": {lean: S.placard(x + 70, head[1] - 50, lean, S.desk_top_y(x + 70) + 6) for lean in LEANS},
        })
    return out


def front():
    o = []
    for role, (bx, by) in (("ceo", (330, 1080)), ("policy", (1110, 1090))):
        col = G.M("coral", 55, "wood") if role == "ceo" else G.M("teal", 55, "wood")
        o.append(f'<g transform="translate({bx},{by}) scale(4.2)">{G.back_person(G.PEOPLE[role])}{GP.armchair_front(col)}</g>')
    o.append('<rect width="1440" height="900" style="fill:url(#shvig)"/>')
    # The foreground and the vignette cover the whole canvas; clicks must reach the delegates.
    return f'<g style="pointer-events:none">{"".join(o)}</g>'


def main():
    root = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
    art = {"back": hall_back(), "seats": seats(), "desk": S.desk(), "front": front()}
    path = os.path.join(root, "ui", "assets", "summitArt.js")
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/office/gen_summit.py; edit the generator, not this file.\n")
        f.write(f"export const ART = {json.dumps(art)};\n")


if __name__ == "__main__":
    main()
